// Array de productos

const products = [ {
    id: 1,
    nombre: "Bennezianna",
    descripción: "La más completa",
    image: "./assets/Bennaziana.png",
    categoria: "pizza",
    isPopular: "yes",
    precio: 3650,
}, {
    id: 2,
    nombre: "Tronco-Pizza",
    descripción: "Para todo el día",
    image: "./assets/Tronco-Pizza.png",
    categoria: "pizza",
    isPopular: "yes",
    precio: 870,
}, {
    id: 3,
    nombre: "La Mr. Pit",
    descripción: "Solo para expertos",
    image: "./assets/mPit.png",
    categoria: "pizza",
    isPopular: "yes",
    precio: 350,
}, {
    id: 4,
    nombre: "¡Q´Jamone!",
    descripción: "C/ jamón crudo",
    image: "./assets/qJamone.png",
    categoria: "pizza",
    isPopular: "no",
    precio: 350,
},{
    id: 5,
    nombre: "La Charly García",
    descripción: "¡BASTA!",
    image: "./assets/charlyGarcia.png",
    categoria: "pizza",
    isPopular: "no",
    precio: 380,
},{
    id: 6,
    nombre: "La Maradona",
    descripción: "¡Eterna!",
    image: "./assets/maradona.png",
    categoria: "pizza",
    isPopular: "no",
    precio: 450,
},{
    id: 7,
    nombre: "Picantovich",
    descripción: "Pica 2 veces",
    image: "./assets/picantovich.png",
    categoria: "pizza",
    isPopular: "no",
    precio: 750,
},{
    id: 8,
    nombre: "La Hasbulla",
    descripción: "En honor al 1",
    image: "./assets/hasbulla.png",
    categoria: "pizza",
    isPopular: "no",
    precio: 990,
},{
    id: 9,
    nombre: "Leo Messi",
    descripción: "¡De pie señores!",
    image: "./assets/messi.png",
    categoria: "pizza",
    isPopular: "no",
    precio: 10,
},{
    id: 10,
    nombre: "Nick Gi",
    descripción: "La que desaparece",
    image: "./assets/nickGi.png",
    categoria: "pizza",
    isPopular: "no",
    precio: "gratis",
},{
    id: 11,
    nombre: "Papas | Provenzal",
    descripción: "Van como piña",
    image: "./assets/papasProvenzal.png",
    categoria: "papas",
    isPopular: "yes",
    precio: 360,
},{
    id: 12,
    nombre: "Salchipapas",
    descripción: "El matrimonio perfecto",
    image: "./assets/salchipapas.png",
    categoria: "papas",
    isPopular: "yes",
    precio: 350,
},{
    id: 13,
    nombre: "Papas Bravas",
    descripción: "Super picantes",
    image: "./assets/papasBravas.png",
    categoria: "papas",
    isPopular: "no",
    precio: 450,
},{
    id: 14,
    nombre: "Onion rings",
    descripción: "Para gobernarlos a todos",
    image: "./assets/onionRings.png",
    categoria: "papas",
    isPopular: "no",
    precio: 350,
},{
    id: 15,
    nombre: "Clásica",
    descripción: "Deliciosa",
    image: "./assets/clasicaBurger.png",
    categoria: "hamburguesa",
    isPopular: "no",
    precio: 750,
},{
    id: 16,
    nombre: "Doble",
    descripción: "Para más placer",
    image: "./assets/doubleBurger.png",
    categoria: "hamburguesa",
    isPopular: "no",
    precio: 950,
},{
    id: 17,
    nombre: "Vegana",
    descripción: "Por todos los animales sintientes",
    image: "./assets/veganaBurger.png",
    categoria: "hamburguesa",
    isPopular: "no",
    precio: 950,
},{
    id: 18,
    nombre: "Spicy",
    descripción: "Para los más aventureros",
    image: "./assets/spicyBurger.png",
    categoria: "hamburguesa",
    isPopular: "yes",
    precio: 1150,
},{
    id: 19,
    nombre: "Con queso",
    descripción: "No hace falta decir más",
    image: "./assets/cheeseBurger.png",
    categoria: "hamburguesa",
    isPopular: "no",
    precio: 850,
},{
    id: 20,
    nombre: "Choriburger",
    descripción: "Mejor que en la cancha",
    image: "./assets/choriBurger.png",
    categoria: "hamburguesa",
    isPopular: "yes",
    precio: 670,
},{
    id: 21,
    nombre: "Limonada",
    descripción: "Si la vida te da limones..",
    image: "./assets/limonada.png",
    categoria: "batidos",
    isPopular: "yes",
    precio: 690,
},{
    id: 22,
    nombre: "Bugs Bunny",
    descripción: "¿Qué hay de nuevo, viejo?",
    image: "./assets/bugsBunny.png",
    categoria: "batidos",
    isPopular: "no",
    precio: 830,
},{
    id: 23,
    nombre: "Verde",
    descripción: "Que te quiero verde",
    image: "./assets/greenSmoothie.png",
    categoria: "batidos",
    isPopular: "yes",
    precio: 700,
},{
    id: 24,
    nombre: "Machado",
    descripción: "Blanca cera y dulce miel",
    image: "./assets/machado.png",
    categoria: "batidos",
    isPopular: "no",
    precio: 780,
},{
    id: 25,
    nombre: "Party on",
    descripción: "Una fiesta de sabores",
    image: "./assets/partyOnWrap.png",
    categoria: "wraps",
    isPopular: "yes",
    precio: 980,
},{
    id: 26,
    nombre: "Arcoiris..",
    descripción: "Todos los colores en un solo wrap",
    image: "./assets/arcoirisWrap.png",
    categoria: "wraps",
    isPopular: "no",
    precio: 950,
},{
    id: 27,
    nombre: "Vegetariano",
    descripción: "¡Mucho más que pasto!",
    image: "./assets/vegetarianoWrap.png",
    categoria: "wraps",
    isPopular: "no",
    precio: 910,
}
];
