// Array de productos

const productsArray = [ {
    id: 1,
    nombre: "Bennezianna",
    descripcion: "La más completa",
    image: "assets/Bennaziana.png",
    categoria: "Pizzas",
    isPopular: "popular",
    precio: 3650,
}, {
    id: 2,
    nombre: "Tronco-Pizzas",
    descripcion: "Para todo el día",
    image: "assets/Tronco-Pizza.png",
    categoria: "Pizzas",
    isPopular: "popular",
    precio: 870,
}, {
    id: 3,
    nombre: "La Mr. Pit",
    descripcion: "Solo para expertos",
    image: "assets/mPit.png",
    categoria: "Pizzas",
    isPopular: "no",
    precio: 350,
}, {
    id: 4,
    nombre: "¡Q´Jamone!",
    descripcion: "C/ jamón crudo",
    image: "assets/qJamone.png",
    categoria: "Pizzas",
    isPopular: "no",
    precio: 350,
},{
    id: 5,
    nombre: "La Charly García",
    descripcion: "¡BASTA!",
    image: "assets/charlyGarcia.png",
    categoria: "Pizzas",
    isPopular: "no",
    precio: 380,
},{
    id: 6,
    nombre: "La Maradona",
    descripcion: "¡Eterna!",
    image: "assets/maradona.png",
    categoria: "Pizzas",
    isPopular: "no",
    precio: 450,
},{
    id: 7,
    nombre: "Picantovich",
    descripcion: "Pica 2 veces",
    image: "assets/picantovich.png",
    categoria: "Pizzas",
    isPopular: "no",
    precio: 750,
},{
    id: 8,
    nombre: "La Hasbulla",
    descripcion: "En honor al 1",
    image: "assets/hasbulla.png",
    categoria: "Pizzas",
    isPopular: "no",
    precio: 990,
},{
    id: 9,
    nombre: "Leo Messi",
    descripcion: "¡De pie señores!",
    image: "assets/messi.png",
    categoria: "Pizzas",
    isPopular: "no",
    precio: 10,
},{
    id: 10,
    nombre: "Nick Gi",
    descripcion: "La que desaparece",
    image: "assets/nickGi.png",
    categoria: "Pizzas",
    isPopular: "no",
    precio: 400,
},{
    id: 11,
    nombre: "Papas | Provenzal",
    descripcion: "Van como piña",
    image: "assets/Papas-Provenzal.png",
    categoria: "Papas",
    isPopular: "popular",
    precio: 360,
},{
    id: 12,
    nombre: "SalchiPapas",
    descripcion: "El matrimonio perfecto",
    image: "assets/salchipapas.png",
    categoria: "Papas",
    isPopular: "popular",
    precio: 350,
},{
    id: 13,
    nombre: "Papas Bravas",
    descripcion: "Super picantes",
    image: "assets/papasBravas.png",
    categoria: "Papas",
    isPopular: "no",
    precio: 450,
},{
    id: 14,
    nombre: "Onion rings",
    descripcion: "Para gobernarlos a todos",
    image: "assets/onionRings.png",
    categoria: "Papas",
    isPopular: "no",
    precio: 350,
},{
    id: 15,
    nombre: "Clásica",
    descripcion: "Deliciosa",
    image: "assets/clasicaBurger.png",
    categoria: "Hamburguesas",
    isPopular: "no",
    precio: 750,
},{
    id: 16,
    nombre: "Doble",
    descripcion: "Para más placer",
    image: "assets/doubleBurger.png",
    categoria: "Hamburguesas",
    isPopular: "no",
    precio: 950,
},{
    id: 17,
    nombre: "Vegana",
    descripcion: "Por todos los animales sintientes",
    image: "assets/veganaBurguer.png",
    categoria: "Hamburguesas",
    isPopular: "no",
    precio: 950,
},{
    id: 18,
    nombre: "Spicy",
    descripcion: "Para los más aventureros",
    image: "assets/spicyBurguer.png",
    categoria: "Hamburguesas",
    isPopular: "popular",
    precio: 1150,
},{
    id: 19,
    nombre: "Con queso",
    descripcion: "No hace falta decir más",
    image: "assets/cheeseBurger.png",
    categoria: "Hamburguesas",
    isPopular: "no",
    precio: 850,
},{
    id: 20,
    nombre: "Choriburger",
    descripcion: "Mejor que en la cancha",
    image: "assets/choriBurger.png",
    categoria: "Hamburguesas",
    isPopular: "popular",
    precio: 670,
},{
    id: 21,
    nombre: "Limonada",
    descripcion: "Si la vida te da limones..",
    image: "assets/limonada.png",
    categoria: "Batidos",
    isPopular: "popular",
    precio: 690,
},{
    id: 22,
    nombre: "Bugs Bunny",
    descripcion: "¿Qué hay de nuevo, viejo?",
    image: "assets/bugsBunny.png",
    categoria: "Batidos",
    isPopular: "no",
    precio: 830,
},{
    id: 23,
    nombre: "Verde",
    descripcion: "Que te quiero verde",
    image: "assets/greenSmoothie.png",
    categoria: "Batidos",
    isPopular: "no",
    precio: 700,
},{
    id: 24,
    nombre: "Machado",
    descripcion: "Blanca cera y dulce miel",
    image: "assets/machado.png",
    categoria: "Batidos",
    isPopular: "no",
    precio: 780,
},{
    id: 25,
    nombre: "Party on",
    descripcion: "Una fiesta de sabores",
    image: "assets/partyOnWrap.png",
    categoria: "Wraps",
    isPopular: "popular",
    precio: 980,
},{
    id: 26,
    nombre: "Arcoiris..",
    descripcion: "Todos los colores en un solo wrap",
    image: "assets/arcoirisWrap.png",
    categoria: "Wraps",
    isPopular: "no",
    precio: 950,
},{
    id: 27,
    nombre: "Vegetariano",
    descripcion: "¡Mucho más que pasto!",
    image: "assets/vegetarianoWrap.png",
    categoria: "Wraps",
    isPopular: "no",
    precio: 910,
}
];